# Generated by Django 4.2.6 on 2023-10-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectPortfolio',
        ),
        migrations.AlterModelOptions(
            name='projectportfolio',
            options={'verbose_name': 'ProjectPortfolio', 'verbose_name_plural': 'ProjectsPortfolio'},
        ),
    ]
