# Generated by Django 4.2.6 on 2023-10-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projectportfolio_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectportfolio',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
