# Generated by Django 4.2.6 on 2023-10-17 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projectportfolio_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectPortfolio',
        ),
    ]
