# Generated by Django 4.2.6 on 2023-10-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0005_delete_projectportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, default='', upload_to='projects/%Y/%m')),
                ('repository_link', models.CharField(max_length=2048)),
                ('deploy_link', models.CharField(max_length=2048)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ProjectPortfolio',
                'verbose_name_plural': 'ProjectsPortfolio',
            },
        ),
    ]
