# Generated by Django 4.2.6 on 2023-10-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_category_projectportfolio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectportfolio',
            name='deploy_link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='projectportfolio',
            name='repository_link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
