# Generated by Django 4.2.6 on 2023-10-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_current_experience',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
