# Generated by Django 4.2.15 on 2024-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_experience_is_current_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_pt',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='description_pt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='title_pt',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectportfolio',
            name='description_pt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectportfolio',
            name='name_pt',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
