# Generated by Django 4.2.10 on 2024-02-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_sectioncontent_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='content',
        ),
        migrations.AddField(
            model_name='section',
            name='contents',
            field=models.ManyToManyField(blank=True, default=None, to='portfolio.sectioncontent'),
        ),
    ]
