# Generated by Django 4.2.6 on 2023-10-19 00:51

from django.db import migrations, models
import utils.models_validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='cv',
            field=models.FileField(blank=True, default='', upload_to='assets/cv/%Y/%m/', validators=[utils.models_validators.validate_pdf]),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', upload_to='assets/profile_pic/%Y/%m/', validators=[utils.models_validators.validate_png]),
        ),
    ]
