# Generated by Django 4.2.15 on 2024-08-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_alter_sitesetup_about_me_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='about_me_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='about_me_pt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='code_languages',
            field=models.TextField(blank=True),
        ),
    ]
