import email.message
import os
import smtplib
from pathlib import Path

from dotenv import load_dotenv

EMAIL_SENDER = "portfolio.rarorza@gmail.com"
EMAIL_DESTINATION = "rarorza@proton.me"

DOTENV_PATH = Path(__file__).parent.parent.parent / "dotenv_files" / ".env"
load_dotenv(dotenv_path=DOTENV_PATH)


def send_email(
    name_form="",
    email_form="",
    message_form="",
    recipient=EMAIL_DESTINATION,
):
    """
    Sending emails requires the password generated by gmail in:
    security > 2-factor authentication > app passwords

    Reference:
    https://support.google.com/accounts/answer/185833
    """
    sender = EMAIL_SENDER
    body_email = f"""
<p>from: {name_form} - {email_form}</p>
<p>message: {message_form}</p>
"""

    msg = email.message.Message()
    msg["Subject"] = "Contact Form"
    msg["From"] = sender
    msg["To"] = recipient
    msg.add_header("Content-Type", "text/html")
    msg.set_payload(body_email)

    # smtp config
    smtp = smtplib.SMTP("smtp.gmail.com: 587")
    smtp.starttls()

    # login
    try:
        password = os.getenv("PWD_SMTP_FORM")
        smtp.login(msg["From"], password)
        smtp.sendmail(msg["From"], [msg["To"]], msg.as_string().encode("utf-8"))
        return True
    except AttributeError:
        return False
